#!/bin/zsh

echo "Sourcing .zshrc"
source "$ZDOTDIR/.zshrc"
echo ""

re_source=false

python_version="3.12.4"

echo "Checking for Pyenv"
if ! command -v pyenv &>/dev/null; then
    echo "Installing Pyenv"
    curl https://pyenv.run | bash
    re_source=true
fi
echo ""

node_version=$(cat $HOME/.node-version)

echo "Checking for node $node_version"
if ! [[ $(fnm ls | grep -w $node_version) ]]; then
    echo "Installing node $node_version"
    fnm install --corepack-enabled
fi
echo ""

if ! command -v node &>/dev/null; then
    fnm use
fi

echo "Checking for pnpm"
if ! command -v pnpm &>/dev/null; then
    echo "Installing pnpm"
    corepack install --global pnpm@latest
fi
echo ""

echo "Checking for Python $python_version"
if ! pyenv versions | grep "$python_version" &>/dev/null; then
    pyenv install $python_version
    pyenv global $python_version
fi
echo ""

echo "Checking for py3nvim virtual environment"
if ! pyenv virtualenvs | grep -w py3nvim &>/dev/null; then
    echo "Creating py3nvim environment"
    pyenv virtualenv py3nvim
    pyenv activate py3nvim
    pip install pynvim
    pyenv deactivate
fi
echo ""

echo "Checking for global neovim pnpm package"
if ! [[ $(pnpm list --global neovim) ]]; then
    echo "Installing global neovim pnpm package"
    pnpm install --global neovim
fi
echo ""

