#!/bin/bash

set -eu

function info_msg {
    echo -e "\e[1;36m>> $1\e[0m"
}

function action_msg {
    echo -e "\e[1;35m>> $1\e[0m"
}

function error_msg {
    echo -e "\e[1;41m>> $1\e[0m"
}

cd "$HOME"

bootstrap_dir=$(dirname "${BASH_SOURCE[0]}")

info_msg "============================"
info_msg "       YADM BOOTSTRAP       "
info_msg "============================"
info_msg ""

info_msg "Checking for sudo command"

if ! command -v sudo &>/dev/null; then
    action_msg "You must install the sudo package before running this script"
    exit 1
fi

action_msg "Initializing yadm submodules"
yadm submodule update --recursive --init

action_msg "Updating pacman packages"
sudo pacman -Syu

action_msg "Installing needed pacman packages"
sudo pacman --needed -S $(cat "$bootstrap_dir/pacman_pkglist")

info_msg "Checking default shell"
if ! [ -n "$($SHELL -c 'echo $ZSH_VERSION')" ]; then
    action_msg "Setting Zsh as the default shell"
    chsh -s $(which zsh)
fi

action_msg "Syncing pkgfile database"
sudo pkgfile -u

info_msg "Checking for Yay"
if ! command -v yay &>/dev/null; then
    action_msg "Installing Yay"
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si
    cd ..
    sudo rm -r yay-bin

    action_msg "Generating development package database"
    yay -Y --gendb
    action_msg "Enabling development package updates"
    yay -Y --devel --save
fi

action_msg "Refreshing Yay database"
yay -Sy

action_msg "Installing needed Yay packages"
yay --needed -S $(cat $bootstrap_dir/yay_pkglist)

action_msg "Enabling systemd services"
sudo systemctl enable thermald
sudo systemctl enable bluetooth

action_msg "Building bat cache"
bat cache --build

info_msg "Checking for Rust compiler"
if ! command -v rustc &>/dev/null; then
    action_msg "Installing Rust"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

info_msg "Checking for rust-analyzer"
if ! rustup component list --installed | grep "rust-analyzer" &>/dev/null; then
    action_msg "Installing rust-analyzer"
    rustup component add rust-analyzer
fi

zsh "${bootstrap_dir}/bootstrap_zsh"

