#!/bin/sh

cd "$HOME"

echo "==========================="
echo "      YADM BOOTSTRAP       "
echo "==========================="
echo ""

echo "Checking for sudo command"
if ! command -v sudo &>/dev/null; then
    echo "You must install the sudo package before running this script"
    exit 1
fi
echo ""

echo "Initializing submodules"
yadm submodule update --recursive --init
echo ""

echo "Refreshing pacman database"
sudo pacman -Sy
echo ""

echo "Installing needed pacman packages"
sudo pacman --needed -S $(cat $HOME/.config/yadm/pacman_pkglist)
echo ""

echo "Checking default shell"
if ! [ -n "$($SHELL -c 'echo $ZSH_VERSION')" ]; then
    echo "Setting Zsh as the default shell"
    chsh -s $(which zsh)
fi
echo ""

echo "Syncing pkgfile database"
sudo pkgfile -u
echo ""

echo "Checking for Yay"
if ! command -v yay &>/dev/null; then
    echo "Installing Yay"
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si
fi
echo ""

echo "Refreshing Yay database"
yay -Sy
echo ""

echo "Installing needed Yay packages"
yay --needed -S $(cat $HOME/.config/yadm/yay_pkglist)
echo ""

echo "Enabling systemd services"
sudo systemctl enable thermald
sudo systemctl enable bluetooth
echo ""

echo "Building bat cache"
bat cache --build
echo ""

echo "Checking for Rust compiler"
if ! command -v rustc &>/dev/null; then
    echo "Installing Rust"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
echo ""

echo "Checking for rust-analyzer"
if ! rustup component list --installed | grep "rust-analyzer" &>/dev/null; then
    echo "Installing rust-analyzer"
    rustup component add rust-analyzer
fi
echo ""

zsh "$HOME/.config/yadm/bootstrap_sourced"

