#!/bin/zsh

echo "Sourcing ~/.zshrc"
source $HOME/.zshrc
echo ""

re_source=false

echo "Checking for nvm"
if ! command -v nvm &>/dev/null; then
    echo "Installing nvm"
    PROFILE=/dev/null bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
    re_source=true
fi
echo ""

python_version="3.12.4"

echo "Checking for Pyenv"
if ! command -v pyenv &>/dev/null; then
    echo "Installing Pyenv"
    curl https://pyenv.run | bash
    re_source=true
fi
echo ""

if $re_source; then
    echo "Re-sourcing ~/.zshrc"
    source "$HOME/.zshrc"
    echo ""
fi

echo "Checking for Python $python_version"
if ! pyenv versions | grep "$python_version" &>/dev/null; then
    pyenv install $python_version
    pyenv global $python_version
fi
echo ""

echo "Checking for py3nvim virtual environment"
if ! pyenv virtualenvs | grep -w py3nvim &>/dev/null; then
    echo "Creating py3nvim environment"
    pyenv virtualenv py3nvim
    pyenv activate py3nvim
    pip install
    pyenv deactivate
fi
echo ""

echo "Setting up node"
nvm install node

echo "Checking for pnpm"
if ! command -v pnpm &>/dev/null; then
    echo "Installing pnpm"
    corepack enable
    corepack install --global pnpm@latest
fi
echo ""

echo "Checking for global neovim pnpm package"
if ! [[ $(pnpm list --global neovim) ]]; then
    echo "Installing global neovim pnpm package"
    pnpm install --global neovim
fi
echo ""

