#!/bin/zsh

set -eu

bootstrap_dir=$(dirname "$0")
source "$bootstrap_dir/common_utils"

info_msg "Sourcing .zshrc"
source "$ZDOTDIR/.zshrc"

NODE_VERSION="v22.5.1"

info_msg "Checking for node $NODE_VERSION"
if ! [[ $(fnm ls | grep -w $NODE_VERSION) ]]; then
    action_msg "Installing node $NODE_VERSION"
    fnm install $NODE_VERSION --corepack-enabled
fi

info_msg "Checking default node version"
if ! [[ $(fnm ls | grep "default" | grep "$NODE_VERSION") ]] then
    action_msg "Setting default node version to $NODE_VERSION"
    fnm default $NODE_VERSION
fi

info_msg "Checking for pnpm"
if ! command -v pnpm &>/dev/null; then
    action_msg "Installing pnpm"
    corepack install --global pnpm@latest
fi

PYTHON_VERSION="3.12.4"

info_msg "Checking for Python $PYTHON_VERSION"
if ! pyenv versions | grep "$PYTHON_VERSION" &>/dev/null; then
    pyenv install $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
fi

info_msg "Checking for py3nvim virtual environment"
if ! pyenv virtualenvs | grep -w py3nvim &>/dev/null; then
    action_msg "Creating py3nvim environment"
    pyenv virtualenv py3nvim
    pyenv activate py3nvim
    pip install pynvim
    pyenv deactivate
fi

info_msg "Checking for global neovim pnpm package"
if ! [[ $(pnpm list --global neovim) ]]; then
    action_msg "Installing global neovim pnpm package"
    pnpm install --global neovim
fi

