let mapleader = ","

set encoding=utf-8
set nocompatible

filetype indent plugin on

set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4

set showmatch
set ignorecase
set hlsearch
set incsearch
set number
set wildmode="longest,list"
set cc=80
set mouse="a"
set clipboard+=unnamedplus
set cursorline

set hidden

set laststatus=2

set ttyfast
set showmode

let g:solarized_termcolors=256
syntax enable
set background=dark
colorscheme solarized
