preload = ~/Pictures/Wallpapers/primary.png
preload = ~/Pictures/Wallpapers/secondary.png

wallpaper = eDP-1,~/Pictures/Wallpapers/primary.png
wallpaper = HDMI-A-1,~/Pictures/Wallpapers/secondary.png
