# Floating programs
windowrule = float, ^([Tt]hunar)$
windowrule = float, ^(org.pulseaudio.pavucontrol)$
windowrule = float, ^(blueman-manager)$
windowrule = float, ^(nm-connection-editor)$
windowrule = float, ^(nvidia-settings)$

# Workspace-specific programs
windowrule = workspace 6, ^(.*)(\.zapzap)$
windowrule = workspace 7, ^(vesktop)$

windowrulev2 = bordercolor rgb(e6c384), pinned:1 # Different border color for pinned windows
windowrulev2 = noborder, fullscreen:1 # Borderless monocle

windowrulev2 = suppressevent maximize, class:.*

