#! /bin/sh

for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
    # polybar hidden when fullscreen for vlc, youtube, mpv ...
    # xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding size

bspc rule -a Gimp desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH"

# sxhkd
pkill sxhkd 2> /dev/null
sxhkd &>> $HOME/.config/sxhkd/.sxhkd.err &

# polybar
pkill polybar 2> /dev/null
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar &

# picom
pkill picom 2> /dev/null
picom --config $HOME/.config/picom/picom.conf &>> ~/.config/picom/.picom.err &

