#! /bin/bash
PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH"

# sxhkd
killall -q sxhkd
sxhkd &>> $HOME/.config/sxhkd/.sxhkd.err &


# # Secondary monitor setup
secondary_monitor=$(xrandr -q | grep 'HDMI-1 connected')

if [[ $secondary_monitor ]];
then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal \
		--output HDMI-1 --mode 1920x1080 --rotate normal --left-of eDP-1

	bspc monitor eDP-1 -d 1 2 3 4 5
	bspc monitor HDMI-1 -d 6 7 8 9 10
	bspc wm -O eDP-1 HDMI-1
else
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal \
		--output HDMI-1 --off

	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi


bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 1

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a discord desktop=^5


# nitrogen
nitrogen --restore &


# picom
killall picom
picom --config $HOME/.config/picom/picom.conf &>> $HOME/.config/picom/.picom.err &


# polybar
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done

polybar main &>> $HOME/.config/polybar/.polybar.err &

if [[ $secondary_monitor ]]; then
	polybar secondary &>> $HOME/.config/polybar/.polybar.err &
fi


