#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding size

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# sxhkd
killall sxhkd 2>/dev/null
sxhkd &>>~/.config/sxhkd/.sxhkd.err &

# polybar
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar &

#picom
killall -9 -qw picom 2>/dev/null; picom --backend xrender --config ~/.config/picom/picom.conf &>>~/.config/picom/.picom.err &
