#!/bin/sh

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="$(playerctl metadata artist) - $(playerctl metadata title)"
fi

MAX_LEN=75

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    color="#c8c093"
elif [[ $player_status = "Paused" ]]; then
    color="#727169"
fi

if [ -z "$color" ]; then
    echo " "
else
    shortened=$(echo "  $metadata" | awk -v len=$MAX_LEN '{ if (length($0) > len) print substr($0, 1, len - 3) "..."; else print; }')
    echo "%{F$color}$shortened%{F-}"
fi
